/* Autogenerated upstream; hardened locally by sync-deltachat-android.sh */
package chat.delta.rpc;

import chat.delta.util.SettableFuture;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/* Basic RPC Transport implementation */
public abstract class BaseRpcTransport implements Rpc.RpcTransport {
  private static final long DEFAULT_CALL_TIMEOUT_SECONDS = 120;

  private final Map<Integer, SettableFuture<JsonNode>> requestFutures = new ConcurrentHashMap<>();
  private final ObjectMapper mapper = new ObjectMapper();
  private final long callTimeout;
  private final TimeUnit callTimeoutUnit;
  private int requestId = 0;
  private volatile Thread worker;

  protected BaseRpcTransport() {
    this(DEFAULT_CALL_TIMEOUT_SECONDS, TimeUnit.SECONDS);
  }

  BaseRpcTransport(long callTimeout, TimeUnit callTimeoutUnit) {
    if (callTimeout <= 0) throw new IllegalArgumentException("callTimeout must be positive");
    if (callTimeoutUnit == null) throw new NullPointerException("callTimeoutUnit");
    this.callTimeout = callTimeout;
    this.callTimeoutUnit = callTimeoutUnit;
  }

  /* Send a Request as raw JSON String to the RPC server */
  protected abstract void sendRequest(String jsonRequest);

  /* Get next Response as raw JSON String from the RPC server */
  protected abstract String getResponse();

  public ObjectMapper getObjectMapper() {
    return mapper;
  }

  public void call(String method, JsonNode... params) throws RpcException {
    innerCall(method, params);
  }

  public <T> T callForResult(TypeReference<T> resultType, String method, JsonNode... params) throws RpcException {
    try {
      JsonNode node = innerCall(method, params);
      if (node.isNull()) return null;
      return mapper.readValue(node.traverse(), resultType);
    } catch (IOException e) {
      throw new RpcException(messageOrClass(e));
    }
  }

  private JsonNode innerCall(String method, JsonNode... params) throws RpcException {
    int id = 0;
    SettableFuture<JsonNode> future = new SettableFuture<>();
    try {
      String jsonRequest;
      synchronized (this) {
        id = ++requestId;
        jsonRequest = mapper.writeValueAsString(new Request(method, params, id));
        requestFutures.put(id, future);
        ensureWorkerThread();
      }
      sendRequest(jsonRequest);
      return future.get(callTimeout, callTimeoutUnit);
    } catch (ExecutionException e) {
      Throwable cause = e.getCause();
      if (cause instanceof RpcException) throw (RpcException) cause;
      throw new RpcException("Delta Chat RPC failed: " + messageOrClass(cause));
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new RpcException("Delta Chat RPC interrupted");
    } catch (TimeoutException e) {
      throw new RpcException("Delta Chat RPC timed out");
    } catch (JsonProcessingException e) {
      throw new RpcException("Delta Chat RPC encoding failed: " + messageOrClass(e));
    } catch (RuntimeException e) {
      throw new RpcException("Delta Chat RPC request failed: " + messageOrClass(e));
    } finally {
      requestFutures.remove(id, future);
    }
  }

  private synchronized void ensureWorkerThread() {
    if (worker != null && worker.isAlive()) return;

    Thread nextWorker = new Thread(this::runWorker, "jsonrpcThread");
    worker = nextWorker;
    nextWorker.start();
  }

  private void runWorker() {
    try {
      while (true) {
        processResponse();
      }
    } catch (RuntimeException | JsonProcessingException e) {
      failPendingRequests(e);
    } finally {
      synchronized (this) {
        if (worker == Thread.currentThread()) worker = null;
      }
    }
  }

  private void failPendingRequests(Throwable cause) {
    RpcException failure = new RpcException("Delta Chat RPC response failed: " + messageOrClass(cause));
    for (Map.Entry<Integer, SettableFuture<JsonNode>> entry : requestFutures.entrySet()) {
      if (requestFutures.remove(entry.getKey(), entry.getValue())) {
        entry.getValue().setException(failure);
      }
    }
  }

  private void processResponse() throws JsonProcessingException {
    String jsonResponse = getResponse();
    Response response = mapper.readValue(jsonResponse, Response.class);

    if (response.id == 0) { // Got JSON-RPC notification/event, ignore
      return;
    }

    SettableFuture<JsonNode> future = requestFutures.remove(response.id);
    if (future == null) { // Got a response with unknown ID, ignore
      return;
    }

    if (response.error != null) {
      future.setException(new RpcException(response.error.message));
    } else if (response.result != null) {
      future.set(response.result);
    } else {
      future.setException(new RpcException("Got JSON-RPC response without result or error: " + jsonResponse));
    }
  }

  int pendingRequestCount() {
    return requestFutures.size();
  }

  Thread workerThread() {
    return worker;
  }

  private static String messageOrClass(Throwable throwable) {
    String message = throwable.getMessage();
    return message == null || message.isEmpty() ? throwable.getClass().getSimpleName() : message;
  }

  private static class Request {
    private final String jsonrpc = "2.0";
    public final String method;
    public final JsonNode[] params;
    public final int id;

    public Request(String method, JsonNode[] params, int id) {
      this.method = method;
      this.params = params;
      this.id = id;
    }
  }

  private static class RpcError {
    public int code;
    public String message;
  }

  private static class Response {
    public String jsonrpc;
    public int id;
    public JsonNode result;
    public RpcError error;
  }
}
