(() => { "use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={source:null,events:[],filter:"all",connected:false};
const fa=n=>new Intl.NumberFormat("fa-IR").format(n);
function config(){return{server:$("#server").value.trim().replace(/\/+$/, ""),topic:$("#topic").value.trim().replace(/^\/+/, ""),token:$("#token").value.trim()}}
function save(){localStorage.setItem("sms-ntfy-dashboard",JSON.stringify(config()))}
function load(){try{const c=JSON.parse(localStorage.getItem("sms-ntfy-dashboard")||"{}");["server","topic","token"].forEach(k=>{if(c[k])$("#"+k).value=c[k]})}catch{}}
function setStatus(kind,text){state.connected=kind==="online";$("#statusPill").className="pill "+kind;$("#statusPill").textContent=text;$("#connectionLabel").textContent=text;$("#sideState").textContent=text;$(".pulse").classList.toggle("connected",state.connected);$("#connectBtn").textContent=state.connected?"قطع اتصال":"اتصال زنده"}
function classify(e){const tags=e.tags||[];if(tags.some(t=>t==="sms"||t==="inbox"))return"sms";if(tags.some(t=>t==="call"||t==="missed"||t==="ringing"))return"call";return"other"}
function escapeHtml(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function render(){const list=state.filter==="all"?state.events:state.events.filter(e=>classify(e)===state.filter);$("#emptyState").hidden=list.length>0;$("#eventList").innerHTML=list.map(e=>`<article class="event"><div class="event-icon">${classify(e)==="sms"?"✉":classify(e)==="call"?"☎":"⚡"}</div><div><h3>${escapeHtml(e.title||"رویداد ntfy")}</h3><p>${escapeHtml(e.message||"")}</p><div class="event-tags">${(e.tags||[]).map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join("")}</div></div><time>${new Date((e.time||Date.now()/1000)*1000).toLocaleTimeString("fa-IR")}</time></article>`).join("");$("#totalCount").textContent=fa(state.events.length);$("#successCount").textContent=fa(state.events.length);$("#eventCount").textContent=fa(list.length)+" رویداد"}
function onMessage(raw){try{const data=JSON.parse(raw.data);if(data.event==="keepalive"||data.event==="open")return;state.events.unshift(data);state.events=state.events.slice(0,200);$("#lastEvent").textContent="آخرین: "+new Date().toLocaleTimeString("fa-IR");render()}catch(e){console.warn("Invalid ntfy event",e)}}
function disconnect(){if(state.source){state.source.close();state.source=null}setStatus("offline","قطع")}
function connect(){disconnect();const c=config();if(!c.server||!c.topic)return;save();setStatus("connecting","در حال اتصال");let url=`${c.server}/${encodeURIComponent(c.topic)}/sse`;if(c.token){url += (url.includes("?")?"&":"?")+"auth="+encodeURIComponent(c.token)}const source=new EventSource(url);state.source=source;source.onopen=()=>setStatus("online","متصل");source.onmessage=onMessage;source.onerror=()=>{if(state.source===source)setStatus("connecting","تلاش مجدد")}}
$("#configForm").addEventListener("submit",e=>{e.preventDefault();connect()});$("#connectBtn").addEventListener("click",()=>state.source?disconnect():connect());$("#clearBtn").addEventListener("click",()=>{state.events=[];render()});$$('[data-filter]').forEach(b=>b.addEventListener("click",()=>{$$('[data-filter]').forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.filter;render()}));$("#themeBtn").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("sms-ntfy-theme",document.body.classList.contains("dark")?"dark":"light")});if(localStorage.getItem("sms-ntfy-theme")==="dark")document.body.classList.add("dark");load();render();window.addEventListener("beforeunload",disconnect);
})();